export const AUDIT_ACTIONS = [
  "USER_CREATED",
  "PRODUCT_CREATED",
  "PRODUCT_UPDATED",
  "PRODUCT_DEACTIVATED",
  "PRODUCT_REACTIVATED",
  "STOCK_SUPPLIED",
  "SALE_CREATED",
  "SALE_CORRECTED",
  "INVENTORY_UPDATED",
  "USER_DEACTIVATED",
  "EXPENSE_CREATED",
  "EXPENSE_UPDATED",
  "EXPENSE_DELETED",
  "STORE_CREATED",
  "STORE_UPDATED",
  "STORE_DEACTIVATED",
] as const;

export type AuditActionValue = (typeof AUDIT_ACTIONS)[number];
